export const AUTH_SIGN_UP = 'AUTH_SIGN_UP' ;
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SIGN_IN='AUTH_SIGN_IN'; 
export const AUTH_SIGN_OUT='AUTH_SIGN_OUT'; 
export const ADD_CV ='ADD_CV';
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SIGN_UP_SOC = "SIGN_UP_SOC";
export const GETJOB = "GETJOB";
export const PROFILE = "PROFILE";
export const REMOVEJOB = "REMOVEJOB" ;
export const MODIFYJOB = "MODIFYJOB0" ;
export const FINDBYTITLE = "FINDBYTITLE"